export const DEFAULT_PLANTS = [
  {
    "id": "snake-plant",
    "name": "Snake Plant",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/3840px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "A hardy, upright plant with stiff sword-like leaves. Tolerates low light and infrequent watering, great for beginners.",
    "cost": "$15",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 4.4
  },
  {
    "id": "spider-plant",
    "name": "Spider Plant",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Hierbabuena_0611_Revised.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Produces long arching leaves and baby plantlets on runners. Easy to grow and purifies indoor air.",
    "cost": "$12",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 4.5
  },
  {
    "id": "peace-lily",
    "name": "Peace Lily",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Glossy dark green leaves with elegant white flowers. Thrives in low light and signals thirst by drooping.",
    "cost": "$18",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 4.6
  },
  {
    "id": "boston-fern",
    "name": "Boston Fern",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/30/Boston_Fern_%282873392811%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A lush, feathery fern that loves humidity. Adds a soft, tropical feel to any room.",
    "cost": "$16",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 4.7
  },
  {
    "id": "zz-plant",
    "name": "ZZ Plant",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Zamioculcas_zamiifolia_1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Waxy, dark green leaves on a plant that survives weeks without water. Nearly indestructible.",
    "cost": "$19",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 4.8
  },
  {
    "id": "golden-pothos",
    "name": "Golden Pothos",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A trailing vine with heart-shaped leaves splashed with gold. Grows fast in almost any light.",
    "cost": "$13",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 4.9
  },
  {
    "id": "areca-palm",
    "name": "Areca Palm",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/22/%E6%95%A3%E5%B0%BE%E8%91%B5Dypsis_lutescens_20210511145013_05.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Feathery fronds that give a breezy, tropical look indoors. Prefers bright, indirect light.",
    "cost": "$28",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 5
  },
  {
    "id": "rubber-plant",
    "name": "Rubber Plant",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/16/Ficus_elastica_leaves_02.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Large, glossy burgundy-green leaves on a sturdy stem. Grows into an impressive floor plant.",
    "cost": "$22",
    "category": "Indoor Plants",
    "sunlight": "Low to Bright Indirect Light",
    "water": "When top inch dries",
    "difficulty": "Beginner",
    "size": "14-24 inches tall",
    "benefit": "Purifies indoor toxins and boosts ambient humidity.",
    "rating": 4.4
  },
  {
    "id": "boxwood",
    "name": "Boxwood",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Buxus_sempervirens.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Dense evergreen shrub popular for hedges and topiary. Handles shaping and shade well.",
    "cost": "$24",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 4.5
  },
  {
    "id": "hydrangea",
    "name": "Hydrangea",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Hydrangea_arborescens_139866012.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Large, showy flower clusters that can change color with soil pH. A classic garden shrub.",
    "cost": "$26",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 4.6
  },
  {
    "id": "rose-bush",
    "name": "Rose Bush",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Rosa_rubiginosa_1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Classic flowering shrub with fragrant blooms in many colors. Needs full sun and regular pruning.",
    "cost": "$20",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 4.7
  },
  {
    "id": "marigold",
    "name": "Marigold",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Tagetes_erecta_chendumalli_chedi.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Bright orange and yellow blooms that are easy to grow and help repel garden pests.",
    "cost": "$6",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 4.8
  },
  {
    "id": "sunflower",
    "name": "Sunflower",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/40/Sunflower_sky_backdrop.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Tall stems topped with large golden flower heads that track the sun across the sky.",
    "cost": "$7",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 4.9
  },
  {
    "id": "english-lavender",
    "name": "English Lavender",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/40/Lavandula_angustifolia_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-087.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Fragrant purple flower spikes on silvery foliage. Drought-tolerant and attracts pollinators.",
    "cost": "$15",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 5
  },
  {
    "id": "hosta",
    "name": "Hosta",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Hosta_Bressingham_Blue.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Shade-loving perennial grown for its broad, textured leaves rather than flowers.",
    "cost": "$14",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 4.4
  },
  {
    "id": "japanese-maple",
    "name": "Japanese Maple",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Acer_palmatum0.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Ornamental tree prized for its delicate, deeply lobed leaves that turn brilliant red in autumn.",
    "cost": "$55",
    "category": "Outdoor Plants",
    "sunlight": "Full Sun (6+ hours daily)",
    "water": "Regular garden watering",
    "difficulty": "Easy",
    "size": "2-4 feet spread",
    "benefit": "Attracts butterflies and beautifies landscape gardens.",
    "rating": 4.5
  },
  {
    "id": "moth-orchid",
    "name": "Moth Orchid",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Elegant arching stems of long-lasting flowers in white, pink, or purple shades.",
    "cost": "$32",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 4.6
  },
  {
    "id": "tropical-hibiscus",
    "name": "Tropical Hibiscus",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/21/Hibiscus_Brilliant.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Large, trumpet-shaped flowers that bloom for a day but keep coming all season.",
    "cost": "$22",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 4.7
  },
  {
    "id": "bird-of-paradise",
    "name": "Bird of Paradise",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Ave-do-para%C3%ADso%2C_Strelitzia_reginae%2C_em_Bag%C3%A9%2C_Rio_Grande_do_Sul%2C_Brasil_-_55211233712.jpg/1920px-Ave-do-para%C3%ADso%2C_Strelitzia_reginae%2C_em_Bag%C3%A9%2C_Rio_Grande_do_Sul%2C_Brasil_-_55211233712.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "Bold banana-like leaves and striking orange-blue flowers resembling a bird in flight.",
    "cost": "$38",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 4.8
  },
  {
    "id": "african-violet",
    "name": "African Violet",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Saintpaulia_ionantha.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Compact plant with fuzzy leaves and clusters of purple, pink, or white flowers. Blooms year-round indoors.",
    "cost": "$14",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 4.9
  },
  {
    "id": "amaryllis",
    "name": "Amaryllis",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/08/Hippeastrum_reginae.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Grows from a bulb into a tall stalk topped with enormous trumpet-shaped flowers.",
    "cost": "$28",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 5
  },
  {
    "id": "bougainvillea",
    "name": "Bougainvillea",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bougainvillea_closeup.jpg/3840px-Bougainvillea_closeup.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "Vigorous vine covered in vivid papery bracts in pink, purple, or orange. Loves full sun.",
    "cost": "$25",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 4.4
  },
  {
    "id": "petunia",
    "name": "Petunia",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Pet%C3%BAnia_%28do_tupi_petyma%2C_%27tabaco%27%29.jpg/1920px-Pet%C3%BAnia_%28do_tupi_petyma%2C_%27tabaco%27%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "Trumpet-shaped flowers in a rainbow of colors, perfect for pots and hanging baskets.",
    "cost": "$8",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 4.5
  },
  {
    "id": "camellia",
    "name": "Camellia",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Camellia_sasanqua1JAM343.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Glossy evergreen shrub with rose-like blooms that flower in cooler months.",
    "cost": "$30",
    "category": "Flowering Plants",
    "sunlight": "Bright Indirect to Partial Sun",
    "water": "Keep soil lightly moist",
    "difficulty": "Intermediate",
    "size": "12-20 inches tall",
    "benefit": "Prolific vibrant blooms with enchanting natural fragrance.",
    "rating": 4.6
  },
  {
    "id": "mexican-snowball",
    "name": "Mexican Snowball",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Echeveria_elegans_-_1.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Rosette-forming succulent with pale blue-white leaves. Extremely low maintenance.",
    "cost": "$9",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 4.7
  },
  {
    "id": "string-of-pearls",
    "name": "String of Pearls",
    "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Senecio_rowleyanus_leaves.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Trailing succulent with tiny bead-like leaves that cascade over pot edges.",
    "cost": "$15",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 4.8
  },
  {
    "id": "aloe-vera",
    "name": "Aloe Vera",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Aloe_vera_flower_inset.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Thick, spiky leaves filled with soothing gel, useful for minor burns and skin care.",
    "cost": "$14",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 4.9
  },
  {
    "id": "golden-barrel-cactus",
    "name": "Golden Barrel Cactus",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Echinocactus_grusonii_%28aka%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Round, ribbed cactus covered in golden spines. A striking desert statement piece.",
    "cost": "$18",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 5
  },
  {
    "id": "jade-plant",
    "name": "Jade Plant",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Crassula_ovata_700.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Thick, glossy oval leaves on woody stems. Said to bring good luck; very easy to care for.",
    "cost": "$16",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 4.4
  },
  {
    "id": "zebra-haworthia",
    "name": "Zebra Haworthia",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5c/1_Haworthia_fasciata_-MBB_Kabeljouws_River.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Small rosette succulent with white striped bumps on dark green leaves.",
    "cost": "$10",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 4.5
  },
  {
    "id": "burro-s-tail",
    "name": "Burro's Tail",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Donkey%27s_tail_in_bloom_March_06.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Trailing succulent with plump, teardrop-shaped leaves that resemble a braided tail.",
    "cost": "$16",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 4.6
  },
  {
    "id": "bunny-ears-cactus",
    "name": "Bunny Ears Cactus",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/36/Opuntia_microdasys_3.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Flat, paddle-shaped pads covered in tiny bristles, growing in a rabbit-ear pattern.",
    "cost": "$14",
    "category": "Succulents and Cacti",
    "sunlight": "Bright Direct Sunlight",
    "water": "Once every 2-3 weeks (drought tolerant)",
    "difficulty": "Beginner",
    "size": "4-10 inches tall",
    "benefit": "Requires minimal water; perfect for bright sunny desks.",
    "rating": 4.7
  },
  {
    "id": "sweet-basil",
    "name": "Sweet Basil",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/97/Ocimum_basilicum_8zz.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Fragrant culinary herb with tender green leaves, essential for pesto and Italian cooking.",
    "cost": "$6",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 4.8
  },
  {
    "id": "peppermint",
    "name": "Peppermint",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/72/Pfefferminze_natur_peppermint.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Fast-spreading aromatic herb used in teas, remedies, and cooking for its cooling flavor.",
    "cost": "$7",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 4.9
  },
  {
    "id": "rosemary",
    "name": "Rosemary",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Rosemary_in_bloom.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Woody, needle-leafed herb with a piney aroma, popular in roasted dishes and traditional remedies.",
    "cost": "$9",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 5
  },
  {
    "id": "ashwagandha",
    "name": "Ashwagandha",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/ad/WithaniaFruit.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A medicinal shrub used in Ayurvedic medicine, valued for its adaptogenic roots.",
    "cost": "$11",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 4.4
  },
  {
    "id": "chamomile",
    "name": "Chamomile",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Matricaria_February_2008-1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Daisy-like flowers dried for a calming, apple-scented herbal tea.",
    "cost": "$8",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 4.5
  },
  {
    "id": "thyme",
    "name": "Thyme",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Thyme-Bundle.jpg/3840px-Thyme-Bundle.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "Low, wiry herb with tiny aromatic leaves, a staple seasoning in many cuisines.",
    "cost": "$6",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 4.6
  },
  {
    "id": "lemongrass",
    "name": "Lemongrass",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Gardenology.org-IMG_2892_rbgs11jan.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Tall, citrus-scented grass used in teas and Southeast Asian cooking.",
    "cost": "$8",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 4.7
  },
  {
    "id": "holy-basil-tulsi",
    "name": "Holy Basil (Tulsi)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/01/Tulsi_or_Tulasi_Holy_basil.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Sacred herb in Indian tradition, brewed as tea and used for its purported immune benefits.",
    "cost": "$7",
    "category": "Herbs and Medicinal Plants",
    "sunlight": "Direct Sunlight / Sunny Windowsill",
    "water": "Keep evenly moist",
    "difficulty": "Easy",
    "size": "8-16 inches tall",
    "benefit": "Fresh aromatic kitchen culinary & therapeutic herbal benefits.",
    "rating": 4.8
  },
  {
    "id": "juniper-bonsai",
    "name": "Juniper Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Juniperus_procumbens_nana_MN_2007.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A classic evergreen bonsai with dense, scale-like foliage, ideal for wiring into dramatic shapes.",
    "cost": "$45",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 4.9
  },
  {
    "id": "ficus-bonsai",
    "name": "Ficus Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Ficus_microcarpa_-_La_Gomera_01.jpg/3840px-Ficus_microcarpa_-_La_Gomera_01.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "A forgiving, indoor-friendly bonsai with small glossy leaves and thick aerial roots.",
    "cost": "$40",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 5
  },
  {
    "id": "chinese-elm-bonsai",
    "name": "Chinese Elm Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/44/RN_Ulmus_parvifolia_%28Hilversum%29.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A popular beginner bonsai with fine branching and small serrated leaves.",
    "cost": "$48",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 4.4
  },
  {
    "id": "jade-bonsai",
    "name": "Jade Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Crassula_ovata_700.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A thick-trunked succulent bonsai style, very tolerant of neglect and low humidity.",
    "cost": "$35",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 4.5
  },
  {
    "id": "japanese-maple-bonsai",
    "name": "Japanese Maple Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Acer_palmatum0.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Delicate, deeply cut leaves that turn brilliant red and orange in autumn.",
    "cost": "$60",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 4.6
  },
  {
    "id": "pine-bonsai",
    "name": "Pine Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Pinus_thunbergii_Izu_Oshima.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A traditional bonsai species with long needles, prized for its rugged, aged appearance.",
    "cost": "$55",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 4.7
  },
  {
    "id": "bougainvillea-bonsai",
    "name": "Bougainvillea Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bougainvillea_closeup.jpg/3840px-Bougainvillea_closeup.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "A flowering bonsai that produces vivid papery bracts when given plenty of sun.",
    "cost": "$42",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 4.8
  },
  {
    "id": "azalea-bonsai",
    "name": "Azalea Bonsai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Alpenroos.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A flowering bonsai covered in vibrant blooms each spring, popular for display shows.",
    "cost": "$50",
    "category": "Bonsai",
    "sunlight": "Bright Filtered Sunlight",
    "water": "Water when surface moss slightly dries",
    "difficulty": "Intermediate",
    "size": "8-15 inches dwarf specimen",
    "benefit": "Ancient living art form promoting mindfulness and tranquility.",
    "rating": 4.9
  },
  {
    "id": "string-of-hearts",
    "name": "String of Hearts",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/Ceropegia_linearis_subsp_woodii.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Delicate trailing vine with heart-shaped, marbled leaves on thin wiry stems.",
    "cost": "$18",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 5
  },
  {
    "id": "hanging-pothos",
    "name": "Hanging Pothos",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A trailing vine version of the classic pothos, perfect for shelves and hanging baskets.",
    "cost": "$14",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 4.4
  },
  {
    "id": "english-ivy",
    "name": "English Ivy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hedera_helix_Dover.jpg/3840px-Hedera_helix_Dover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "Fast-growing trailing vine with lobed leaves, often grown in hanging pots or as ground cover.",
    "cost": "$14",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 4.5
  },
  {
    "id": "trailing-spider-plant",
    "name": "Trailing Spider Plant",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Hierbabuena_0611_Revised.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Arching leaves and cascading plantlets make this a natural fit for a hanging basket.",
    "cost": "$13",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 4.6
  },
  {
    "id": "hanging-burro-s-tail",
    "name": "Hanging Burro's Tail",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Donkey%27s_tail_in_bloom_March_06.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Long, trailing strands of plump succulent leaves that drape beautifully from a hanging pot.",
    "cost": "$17",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 4.7
  },
  {
    "id": "hanging-boston-fern",
    "name": "Hanging Boston Fern",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/30/Boston_Fern_%282873392811%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Full, feathery fronds that spill gracefully over the sides of a hanging planter.",
    "cost": "$18",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 4.8
  },
  {
    "id": "philodendron-micans",
    "name": "Philodendron Micans",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Philodendron_scandens_subsp_oxycardium2.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Velvety, heart-shaped leaves with a shimmering bronze-green sheen on trailing stems.",
    "cost": "$20",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 4.9
  },
  {
    "id": "dischidia-million-hearts",
    "name": "Dischidia Million Hearts",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/%E7%99%BE%E8%90%AC%E5%BF%83_Dischidia_ruscifolia_-%E9%A6%99%E6%B8%AF%E5%8B%95%E6%A4%8D%E7%89%A9%E5%85%AC%E5%9C%92_Hong_Kong_Botanical_Garden-_%289240152650%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Tiny round succulent-like leaves densely packed along thin trailing stems.",
    "cost": "$19",
    "category": "Hanging Plants",
    "sunlight": "Bright Indirect Light",
    "water": "Weekly soaking or misting",
    "difficulty": "Easy",
    "size": "Trailing 2-4 feet",
    "benefit": "Graceful cascading vines that maximize vertical room space.",
    "rating": 5
  },
  {
    "id": "terracotta-pot-8-inch",
    "name": "Terracotta Pot (8-inch)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9a/%22Meillandine%22_Rose_in_clay_pot.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Classic breathable clay pot that helps prevent overwatering. Fits most medium plants.",
    "cost": "$10",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 4.4
  },
  {
    "id": "copper-watering-can",
    "name": "Copper Watering Can",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1b/MetalwateringcansDec08.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A long-spout watering can for precise, gentle watering of indoor and patio plants.",
    "cost": "$22",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 4.5
  },
  {
    "id": "garden-trowel",
    "name": "Garden Trowel",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/93/Masons_trowel.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A hand-held digging tool for potting, transplanting, and weeding.",
    "cost": "$8",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 4.6
  },
  {
    "id": "pruning-shears",
    "name": "Pruning Shears",
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Secateur_ouvert.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Sharp bypass shears for clean cuts when trimming stems, leaves, and small branches.",
    "cost": "$15",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 4.7
  },
  {
    "id": "organic-plant-fertilizer",
    "name": "Organic Plant Fertilizer",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/53/Manure_spreading_Hlokozi_2007_11_29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A balanced, slow-release fertilizer to keep houseplants and garden beds healthy.",
    "cost": "$12",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 4.8
  },
  {
    "id": "led-grow-light",
    "name": "LED Grow Light",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Aspect_Black_20W_Growlight_over_Bonsai.jpg/3840px-Aspect_Black_20W_Growlight_over_Bonsai.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "description": "A compact full-spectrum light that supplements sunlight for low-light indoor plants.",
    "cost": "$30",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 4.9
  },
  {
    "id": "plant-mister-spray-bottle",
    "name": "Plant Mister Spray Bottle",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Action_photo_of_nasal_spray_on_a_black_background.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "A fine-mist spray bottle for raising humidity around ferns and tropical plants.",
    "cost": "$7",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 5
  },
  {
    "id": "gardening-gloves",
    "name": "Gardening Gloves",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/01/Centre_de_Documentaci%C3%B3_Museu_T%C3%A8xtil_de_Terrassa-_Reserves-_Teixits-_Guants002.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
    "description": "Durable, breathable gloves that protect hands while potting, pruning, and weeding.",
    "cost": "$9",
    "category": "Gardening Accessories",
    "sunlight": "N/A (Essential Garden Tool)",
    "water": "N/A",
    "difficulty": "Easy to Use",
    "size": "Standard Ergonomic Size",
    "benefit": "Durable premium tool essential for happy, thriving houseplants.",
    "rating": 4.4
  }
];
