export const DEFAULT_PLANTS = [
  // ==========================================
  // 1. AIR PURIFYING (10 Plants)
  // ==========================================
  {
    id: 'snake-plant',
    name: "Snake Plant",
    image: "https://cdn.pixabay.com/photo/2021/01/22/06/04/snake-plant-5939187_1280.jpg",
    description: "Produces oxygen at night, perfect for bedroom air filtration.",
    cost: "$15",
    category: "Air Purifying",
    sunlight: "Indirect Light / Partial Shade",
    water: "Once every 2-3 weeks",
    difficulty: "Beginner",
    size: "12-18 inches tall",
    benefit: "Cleans benzene, formaldehyde, trichloroethylene, and xylene from the air.",
    rating: 4.8
  },
  {
    id: 'spider-plant',
    name: "Spider Plant",
    image: "https://cdn.pixabay.com/photo/2018/07/11/06/47/chlorophytum-3530413_1280.jpg",
    description: "Highly effective at filtering indoor air toxins and producing baby offsets.",
    cost: "$12",
    category: "Air Purifying",
    sunlight: "Bright Indirect Light",
    water: "Once a week",
    difficulty: "Easy",
    size: "8-12 inches tall",
    benefit: "Thrives in humid conditions; safely non-toxic for cats and dogs.",
    rating: 4.5
  },
  {
    id: 'peace-lily',
    name: "Peace Lily",
    image: "https://cdn.pixabay.com/photo/2019/06/12/14/14/peace-lilies-4269365_1280.jpg",
    description: "Stunning white blooms that filter harmful chemicals and signal thirst.",
    cost: "$18",
    category: "Air Purifying",
    sunlight: "Low to Medium Light",
    water: "Keep soil damp, mist leaves weekly",
    difficulty: "Medium",
    size: "18-24 inches tall",
    benefit: "Produces beautiful white spathes that break down acetone and ammonia.",
    rating: 4.6
  },
  {
    id: 'boston-fern',
    name: "Boston Fern",
    image: "https://cdn.pixabay.com/photo/2020/04/30/19/52/boston-fern-5114414_1280.jpg",
    description: "Lush, feathery arching fronds that naturally humidify room air.",
    cost: "$16",
    category: "Air Purifying",
    sunlight: "Filtered Medium Light",
    water: "Keep consistently moist; love misting",
    difficulty: "Intermediate",
    size: "16-24 inches spread",
    benefit: "Acts as a natural humidifier and absorbs airborne formaldehydes.",
    rating: 4.7
  },
  {
    id: 'english-ivy',
    name: "English Ivy",
    image: "https://cdn.pixabay.com/photo/2017/08/07/14/02/ivy-2604169_1280.jpg",
    description: "Cascading evergreen vine with classic variegated star-shaped leaves.",
    cost: "$14",
    category: "Air Purifying",
    sunlight: "Bright Indirect Sunlight",
    water: "Water when top 1 inch is dry",
    difficulty: "Easy",
    size: "Trailing up to 36 inches",
    benefit: "Reduces airborne mold particles by up to 78% in enclosed spaces.",
    rating: 4.4
  },
  {
    id: 'areca-palm',
    name: "Areca Palm",
    image: "https://cdn.pixabay.com/photo/2016/11/29/03/42/indoor-plants-1867118_1280.jpg",
    description: "Tropical graceful palm fronds that bring a resort feel indoors.",
    cost: "$28",
    category: "Air Purifying",
    sunlight: "Bright Filtered Sunlight",
    water: "Water when top half of soil dries",
    difficulty: "Easy",
    size: "3-5 feet tall",
    benefit: "Transpires up to 1 liter of moisture per 24 hours into dry indoor air.",
    rating: 4.8
  },
  {
    id: 'rubber-tree',
    name: "Burgundy Rubber Tree",
    image: "https://cdn.pixabay.com/photo/2020/02/15/11/49/flower-4850729_1280.jpg",
    description: "Broad, thick glossy deep emerald and burgundy statement foliage.",
    cost: "$22",
    category: "Air Purifying",
    sunlight: "Bright Indirect Light",
    water: "Allow top 2 inches to dry between waterings",
    difficulty: "Easy",
    size: "24-36 inches tall",
    benefit: "Large leaf surface area captures high amounts of airborne dust.",
    rating: 4.7
  },
  {
    id: 'bamboo-palm',
    name: "Bamboo Palm",
    image: "https://cdn.pixabay.com/photo/2018/03/02/18/43/indoor-plant-3193910_1280.jpg",
    description: "Dense, tall cluster of bamboo-like stems with rich green fronds.",
    cost: "$26",
    category: "Air Purifying",
    sunlight: "Medium to Low Light",
    water: "Keep evenly moist but well-drained",
    difficulty: "Beginner",
    size: "3-4 feet tall",
    benefit: "Rated among top air scrubbers for carbon monoxide and xylene.",
    rating: 4.6
  },
  {
    id: 'dracaena-marginata',
    name: "Dragon Tree (Dracaena)",
    image: "https://cdn.pixabay.com/photo/2019/04/10/11/56/dracaena-4116812_1280.jpg",
    description: "Sculptural slender trunk topped with ribbons of red-edged leaves.",
    cost: "$20",
    category: "Air Purifying",
    sunlight: "Low to Bright Indirect Light",
    water: "Allow soil to dry slightly between waterings",
    difficulty: "Beginner",
    size: "24-30 inches tall",
    benefit: "Highly tolerant of lower light and irregular watering schedules.",
    rating: 4.5
  },
  {
    id: 'chinese-evergreen',
    name: "Chinese Evergreen (Aglaonema)",
    image: "https://cdn.pixabay.com/photo/2020/07/18/14/16/aglaonema-5417329_1280.jpg",
    description: "Patterned silver-and-green broad leaves that thrive in offices.",
    cost: "$19",
    category: "Air Purifying",
    sunlight: "Low to Medium Indirect Light",
    water: "Every 1-2 weeks",
    difficulty: "Beginner",
    size: "14-20 inches tall",
    benefit: "Continues to emit oxygen and filter toxins under fluorescent lighting.",
    rating: 4.6
  },

  // ==========================================
  // 2. AROMATIC & FRAGRANT (10 Plants)
  // ==========================================
  {
    id: 'lavender',
    name: "French Lavender",
    image: "https://images.unsplash.com/photo-1611909023032-2d6b3134ecba?q=80&w=600&auto=format&fit=crop",
    description: "Calming sweet botanical scent that reduces stress and improves sleep.",
    cost: "$20",
    category: "Aromatic Fragrant",
    sunlight: "Full Sun (6+ hours daily)",
    water: "Only when soil is completely dry",
    difficulty: "Medium",
    size: "12-16 inches tall",
    benefit: "Releases therapeutic essential oils that naturally induce relaxation.",
    rating: 4.9
  },
  {
    id: 'jasmine',
    name: "Star Jasmine",
    image: "https://images.unsplash.com/photo-1592729645009-b96d1e63d14b?q=80&w=600&auto=format&fit=crop",
    description: "Intensely sweet floral perfume from star-shaped pristine white blossoms.",
    cost: "$22",
    category: "Aromatic Fragrant",
    sunlight: "Bright Light, Direct Morning Sun",
    water: "Keep evenly moist but not waterlogged",
    difficulty: "Intermediate",
    size: "24-36 inches (climbing vine)",
    benefit: "Aromatherapy proven to relieve nervous tension and elevate mood.",
    rating: 4.7
  },
  {
    id: 'rosemary',
    name: "Tuscan Rosemary",
    image: "https://cdn.pixabay.com/photo/2019/10/11/07/12/rosemary-4541241_1280.jpg",
    description: "Aromatic needle-like foliage with an invigorating pine and herbal fragrance.",
    cost: "$10",
    category: "Aromatic Fragrant",
    sunlight: "Full, Direct Sun",
    water: "Low water requirements; drought-tolerant",
    difficulty: "Easy",
    size: "10-15 inches tall",
    benefit: "Fresh kitchen herb that stimulates memory recall and repels pests.",
    rating: 4.4
  },
  {
    id: 'sweet-basil',
    name: "Genovese Sweet Basil",
    image: "https://cdn.pixabay.com/photo/2014/04/05/11/40/basil-316616_1280.jpg",
    description: "Classic Italian culinary herb with sweet, spicy anise-clove aroma.",
    cost: "$8",
    category: "Aromatic Fragrant",
    sunlight: "Direct Sunlight",
    water: "Keep soil consistently moist",
    difficulty: "Beginner",
    size: "8-12 inches tall",
    benefit: "Harvest fresh leaves for homemade pesto, pastas, and cocktails.",
    rating: 4.6
  },
  {
    id: 'gardenia',
    name: "Gardenia Cape Jasmine",
    image: "https://cdn.pixabay.com/photo/2017/07/12/12/23/gardenia-2496839_1280.jpg",
    description: "Velvety white petals with an unforgettable, luxurious floral scent.",
    cost: "$24",
    category: "Aromatic Fragrant",
    sunlight: "Bright Indirect Light with High Humidity",
    water: "Water with room-temperature water when topsoil dries",
    difficulty: "Intermediate",
    size: "16-22 inches tall",
    benefit: "Natural luxury scent that perfumes an entire living room.",
    rating: 4.8
  },
  {
    id: 'peppermint',
    name: "Crisp Peppermint",
    image: "https://cdn.pixabay.com/photo/2016/01/05/17/51/mint-1123188_1280.jpg",
    description: "Refreshing cooling menthol scent that invigorates focus and alertness.",
    cost: "$9",
    category: "Aromatic Fragrant",
    sunlight: "Partial Sun to Light Shade",
    water: "Keep damp; loves moisture",
    difficulty: "Beginner",
    size: "10-14 inches tall",
    benefit: "Brew fresh soothing mint tea for natural digestive comfort.",
    rating: 4.5
  },
  {
    id: 'lemon-balm',
    name: "Lemon Balm",
    image: "https://cdn.pixabay.com/photo/2017/05/29/19/27/lemon-balm-2354673_1280.jpg",
    description: "Bright citrus-mint fragrance released whenever leaves are brushed.",
    cost: "$11",
    category: "Aromatic Fragrant",
    sunlight: "Full Sun to Partial Shade",
    water: "Water when top 1 inch dries",
    difficulty: "Easy",
    size: "12-16 inches tall",
    benefit: "Contains rosmarinic acid which aids in stress reduction.",
    rating: 4.4
  },
  {
    id: 'eucalyptus',
    name: "Silver Dollar Eucalyptus",
    image: "https://cdn.pixabay.com/photo/2019/09/27/09/48/eucalyptus-4507986_1280.jpg",
    description: "Blue-green rounded leaves with a soothing spa-like balsamic aroma.",
    cost: "$25",
    category: "Aromatic Fragrant",
    sunlight: "Bright Direct Sun",
    water: "Moderate; allow top soil to dry",
    difficulty: "Medium",
    size: "20-30 inches tall",
    benefit: "Clears respiratory passages and dries into everlasting floral stems.",
    rating: 4.9
  },
  {
    id: 'arabian-jasmine',
    name: "Mogra (Arabian Jasmine)",
    image: "https://cdn.pixabay.com/photo/2021/07/19/04/36/jasmine-6477123_1280.jpg",
    description: "Heavily scented traditional jasmine used for floral garlands and tea.",
    cost: "$21",
    category: "Aromatic Fragrant",
    sunlight: "Full Morning Sun",
    water: "Regular watering; drain well",
    difficulty: "Intermediate",
    size: "18-28 inches tall",
    benefit: "Blooms repeatedly throughout warm months with enchanting evening fragrance.",
    rating: 4.8
  },
  {
    id: 'scented-geranium',
    name: "Citronella Scented Geranium",
    image: "https://cdn.pixabay.com/photo/2018/05/10/19/47/geranium-3388514_1280.jpg",
    description: "Lobed velvety leaves with a punchy lemon-citronella mosquito-repelling aroma.",
    cost: "$13",
    category: "Aromatic Fragrant",
    sunlight: "Sunny Windowsill",
    water: "Water thoroughly when dry",
    difficulty: "Beginner",
    size: "12-18 inches tall",
    benefit: "Natural outdoor and balcony mosquito deterrent.",
    rating: 4.3
  },

  // ==========================================
  // 3. LOW MAINTENANCE (10 Plants)
  // ==========================================
  {
    id: 'aloe-vera',
    name: "Aloe Vera",
    image: "https://cdn.pixabay.com/photo/2018/04/02/07/42/leaf-3283175_1280.jpg",
    description: "Fleshy serrated spears packed with pure soothing therapeutic gel.",
    cost: "$14",
    category: "Low Maintenance",
    sunlight: "Bright Indirect Sunlight",
    water: "Once every 3 weeks",
    difficulty: "Beginner",
    size: "10-14 inches tall",
    benefit: "Gel can be harvested to naturally soothe minor kitchen burns and skin dryness.",
    rating: 4.8
  },
  {
    id: 'cast-iron-plant',
    name: "Cast Iron Plant",
    image: "https://cdn.pixabay.com/photo/2020/09/24/16/12/houseplants-5600122_1280.jpg",
    description: "Indestructible dark green foliage that survives neglect and low light.",
    cost: "$25",
    category: "Low Maintenance",
    sunlight: "Low light to Deep Shade",
    water: "Allow soil to dry fully between waterings",
    difficulty: "Beginner",
    size: "20-28 inches tall",
    benefit: "Survives temperature fluctuations, drafts, and forgotten waterings.",
    rating: 4.3
  },
  {
    id: 'zz-plant',
    name: "ZZ Plant (Zamioculcas)",
    image: "https://cdn.pixabay.com/photo/2021/04/21/09/03/zamioculcas-6195821_1280.jpg",
    description: "Glossy mirror-shine leaves that store water in thick underground tubers.",
    cost: "$19",
    category: "Low Maintenance",
    sunlight: "Low to Bright Indirect Light",
    water: "Once a month (highly drought-tolerant)",
    difficulty: "Beginner",
    size: "18-24 inches tall",
    benefit: "Perfect plant for travelers, windowless offices, and beginner plant parents.",
    rating: 4.7
  },
  {
    id: 'pothos-golden',
    name: "Golden Pothos (Devil's Ivy)",
    image: "https://cdn.pixabay.com/photo/2020/12/10/10/17/pothos-5820061_1280.jpg",
    description: "Fast-growing heart-shaped leaves splashed with gold variegation.",
    cost: "$13",
    category: "Low Maintenance",
    sunlight: "Any light level except direct burning sun",
    water: "Every 7-10 days",
    difficulty: "Beginner",
    size: "Trails 4-8 feet",
    benefit: "Super easy to propagate cuttings directly in a glass of water.",
    rating: 4.9
  },
  {
    id: 'jade-plant',
    name: "Lucky Jade Plant",
    image: "https://cdn.pixabay.com/photo/2018/05/08/17/23/succulent-3383478_1280.jpg",
    description: "Tree-like succulent bonsai featuring plump oval jade-green leaves.",
    cost: "$16",
    category: "Low Maintenance",
    sunlight: "Bright Light with direct sun",
    water: "Once every 2-3 weeks",
    difficulty: "Beginner",
    size: "10-16 inches tall",
    benefit: "Symbol of wealth and prosperity in Feng Shui traditions.",
    rating: 4.7
  },
  {
    id: 'pilea-peperomioides',
    name: "Pilea Peperomioides (UFO Plant)",
    image: "https://cdn.pixabay.com/photo/2020/07/14/09/25/pilea-5403487_1280.jpg",
    description: "Playful round coin-like leaves balanced gracefully on arching stems.",
    cost: "$17",
    category: "Low Maintenance",
    sunlight: "Bright Indirect Sunlight",
    water: "Allow top half of soil to dry",
    difficulty: "Easy",
    size: "8-12 inches tall",
    benefit: "Regularly produces easy-to-share baby 'pass-it-on' plantlets.",
    rating: 4.8
  },
  {
    id: 'haworthia-fasciata',
    name: "Zebra Haworthia",
    image: "https://cdn.pixabay.com/photo/2019/03/07/12/36/succulent-4040103_1280.jpg",
    description: "Compact rosettes adorned with raised horizontal white pearl stripes.",
    cost: "$10",
    category: "Low Maintenance",
    sunlight: "Bright Indirect to Partial Sun",
    water: "Once every 3-4 weeks",
    difficulty: "Beginner",
    size: "4-6 inches tall",
    benefit: "Compact desk buddy that requires almost zero attention.",
    rating: 4.6
  },
  {
    id: 'ponytail-palm',
    name: "Ponytail Palm",
    image: "https://cdn.pixabay.com/photo/2019/11/04/07/35/ponytail-palm-4600492_1280.jpg",
    description: "Bulbous elephant-foot base with fountains of slender curly leaves.",
    cost: "$29",
    category: "Low Maintenance",
    sunlight: "Bright Indirect to Full Sun",
    water: "Once a month (swollen trunk stores water)",
    difficulty: "Beginner",
    size: "20-30 inches tall",
    benefit: "Completely non-toxic to cats and naturally whimsical statement piece.",
    rating: 4.7
  },
  {
    id: 'sansevieria-moonshine',
    name: "Moonshine Silver Sansevieria",
    image: "https://cdn.pixabay.com/photo/2020/05/21/18/44/sansevieria-5202157_1280.jpg",
    description: "Architectural upright broad leaves in a mesmerizing silvery pale mint color.",
    cost: "$21",
    category: "Low Maintenance",
    sunlight: "Low to Bright Indirect Light",
    water: "Every 3 weeks",
    difficulty: "Beginner",
    size: "14-20 inches tall",
    benefit: "Modern chic aesthetic that tolerates low-light corners.",
    rating: 4.8
  },
  {
    id: 'aglaonema-silver-bay',
    name: "Silver Bay Chinese Evergreen",
    image: "https://cdn.pixabay.com/photo/2020/04/18/14/02/flower-5059438_1280.jpg",
    description: "Broad luminous silver centers surrounded by deep forest green borders.",
    cost: "$23",
    category: "Low Maintenance",
    sunlight: "Low to Filtered Medium Light",
    water: "When top 2 inches dry out",
    difficulty: "Beginner",
    size: "18-24 inches spread",
    benefit: "Loves typical indoor temperatures and needs very little humidity.",
    rating: 4.6
  },

  // ==========================================
  // 4. SUCCULENTS & CACTI (10 Plants)
  // ==========================================
  {
    id: 'echeveria-elegans',
    name: "Mexican Snowball (Echeveria)",
    image: "https://cdn.pixabay.com/photo/2017/08/07/19/07/succulent-2607147_1280.jpg",
    description: "Geometric rosette succulent with powder-blue fleshy rounded petals.",
    cost: "$9",
    category: "Succulents & Cacti",
    sunlight: "Direct Bright Sun",
    water: "Soak and dry completely every 2 weeks",
    difficulty: "Beginner",
    size: "4-6 inches wide",
    benefit: "Coated in farina wax that protects against UV radiation.",
    rating: 4.8
  },
  {
    id: 'string-of-pearls',
    name: "String of Pearls (Senecio)",
    image: "https://cdn.pixabay.com/photo/2020/09/05/11/04/senecio-5546258_1280.jpg",
    description: "Delicate cascading tendrils adorned with sphere-shaped green pea beads.",
    cost: "$15",
    category: "Succulents & Cacti",
    sunlight: "Bright Indirect Light",
    water: "When pearl beads start to slightly pucker",
    difficulty: "Intermediate",
    size: "Trails 12-24 inches",
    benefit: "Breathtaking hanging basket succulent for bright sunny windows.",
    rating: 4.7
  },
  {
    id: 'fairy-washboard',
    name: "Fairy Washboard Cactus",
    image: "https://cdn.pixabay.com/photo/2016/11/21/16/08/cactus-1846147_1280.jpg",
    description: "Ridged triangular succulent rosettes with deep green textured leaves.",
    cost: "$11",
    category: "Succulents & Cacti",
    sunlight: "Bright Filtered Light",
    water: "Every 3 weeks",
    difficulty: "Beginner",
    size: "5-7 inches tall",
    benefit: "Hardy architectural desktop succulent that requires minimal care.",
    rating: 4.5
  },
  {
    id: 'burros-tail',
    name: "Burro's Tail (Sedum)",
    image: "https://cdn.pixabay.com/photo/2020/05/04/10/15/sedum-5128637_1280.jpg",
    description: "Braided heavy cascading stems densely packed with plump teardrop leaves.",
    cost: "$16",
    category: "Succulents & Cacti",
    sunlight: "Bright Direct Sun",
    water: "Allow soil to completely dry out",
    difficulty: "Easy",
    size: "Trailing 12-20 inches",
    benefit: "Mesmerizing blue-green hanging foliage that tolerates dry heat.",
    rating: 4.6
  },
  {
    id: 'bunny-ears-cactus',
    name: "Bunny Ears Cactus (Opuntia)",
    image: "https://cdn.pixabay.com/photo/2018/08/29/19/01/cactus-3640523_1280.jpg",
    description: "Pair of pad-like stems dotted with golden glochid tufts looking like rabbit ears.",
    cost: "$14",
    category: "Succulents & Cacti",
    sunlight: "Maximum Direct Sun",
    water: "Monthly in summer, zero in winter",
    difficulty: "Beginner",
    size: "8-14 inches tall",
    benefit: "Classic desert cactus requiring virtually no water.",
    rating: 4.4
  },
  {
    id: 'crassula-gollum',
    name: "Gollum Jade Succulent",
    image: "https://cdn.pixabay.com/photo/2018/03/18/15/07/crassula-3237071_1280.jpg",
    description: "Funky tubular leaves with suction-cup tips that blush red in bright sun.",
    cost: "$12",
    category: "Succulents & Cacti",
    sunlight: "Bright Sunny Exposure",
    water: "Every 2-3 weeks",
    difficulty: "Easy",
    size: "8-12 inches tall",
    benefit: "Bonsai-like trunk develops with age; extremely sturdy.",
    rating: 4.7
  },
  {
    id: 'moon-cactus',
    name: "Ruby Ball Moon Cactus",
    image: "https://cdn.pixabay.com/photo/2017/07/28/14/29/cactus-2548827_1280.jpg",
    description: "Vibrant neon-red or hot-pink grafted orb sitting atop a green cactus stem.",
    cost: "$13",
    category: "Succulents & Cacti",
    sunlight: "Bright Indirect Light",
    water: "Every 2-3 weeks",
    difficulty: "Beginner",
    size: "4-6 inches tall",
    benefit: "Injects electric candy colors into modern home office desks.",
    rating: 4.6
  },
  {
    id: 'string-of-hearts',
    name: "String of Hearts (Ceropegia)",
    image: "https://cdn.pixabay.com/photo/2021/06/15/12/28/ceropegia-woodii-6338499_1280.jpg",
    description: "Wire-thin purple vines dotted with heart-shaped mottled silver leaves.",
    cost: "$18",
    category: "Succulents & Cacti",
    sunlight: "Bright Filtered Light",
    water: "When soil dries completely; water from below",
    difficulty: "Easy",
    size: "Trailing up to 4 feet",
    benefit: "Fast grower that creates a curtain of romantic heart leaves.",
    rating: 4.9
  },
  {
    id: 'blue-chalksticks',
    name: "Blue Chalksticks (Senecio)",
    image: "https://cdn.pixabay.com/photo/2019/08/04/09/44/succulents-4383407_1280.jpg",
    description: "Upright powder-blue succulent fingers that form dense colorful mats.",
    cost: "$10",
    category: "Succulents & Cacti",
    sunlight: "Full Direct Sun",
    water: "Every 3 weeks",
    difficulty: "Beginner",
    size: "6-10 inches tall",
    benefit: "Provides rare vibrant turquoise color contrast in succulent planters.",
    rating: 4.5
  },
  {
    id: 'bishops-cap',
    name: "Bishop's Cap (Astrophytum)",
    image: "https://cdn.pixabay.com/photo/2016/09/01/19/53/astrophytum-1637374_1280.jpg",
    description: "Spineless star-shaped cactus resembling a bishop's ceremonial mitre.",
    cost: "$17",
    category: "Succulents & Cacti",
    sunlight: "Bright Direct Sun",
    water: "Spare watering only during growing season",
    difficulty: "Medium",
    size: "4-5 inches wide",
    benefit: "Rare collector cactus that produces silk-yellow daisy flowers.",
    rating: 4.8
  },

  // ==========================================
  // 5. FLOWERING & EXOTIC (10 Plants)
  // ==========================================
  {
    id: 'phalaenopsis-orchid',
    name: "Royal Moth Orchid (Phalaenopsis)",
    image: "https://cdn.pixabay.com/photo/2017/03/07/18/04/orchid-2124773_1280.jpg",
    description: "Majestic arching sprays of exotic moth-like long-lasting butterfly blooms.",
    cost: "$32",
    category: "Flowering & Exotic",
    sunlight: "Medium to Bright Indirect Light",
    water: "Ice cube method or weekly bark drench",
    difficulty: "Intermediate",
    size: "18-24 inches tall",
    benefit: "Flowers persist for up to 3 months straight per blooming cycle.",
    rating: 4.9
  },
  {
    id: 'anthurium-red',
    name: "Flamingo Flower (Anthurium Red)",
    image: "https://cdn.pixabay.com/photo/2019/04/08/20/46/anthurium-4112959_1280.jpg",
    description: "Glossy lipstick-red heart spathes with contrasting yellow flower spadix.",
    cost: "$27",
    category: "Flowering & Exotic",
    sunlight: "Bright Indirect Light",
    water: "Keep soil slightly moist; mist often",
    difficulty: "Easy",
    size: "14-18 inches tall",
    benefit: "The world's longest-blooming indoor houseplant (blooms year-round).",
    rating: 4.7
  },
  {
    id: 'bird-of-paradise',
    name: "Bird of Paradise (Strelitzia)",
    image: "https://cdn.pixabay.com/photo/2018/04/29/11/59/strelitzia-3359765_1280.jpg",
    description: "Iconic banana-like grand paddle leaves and crane-shaped orange flowers.",
    cost: "$38",
    category: "Flowering & Exotic",
    sunlight: "Bright Direct to Indirect Sunlight",
    water: "Water when top 2 inches dry out",
    difficulty: "Medium",
    size: "4-6 feet tall",
    benefit: "The ultimate tropical luxury interior design statement tree.",
    rating: 4.9
  },
  {
    id: 'african-violet',
    name: "African Violet (Saintpaulia)",
    image: "https://cdn.pixabay.com/photo/2018/03/14/19/04/african-violet-3226065_1280.jpg",
    description: "Fuzzy velvet rosettes blooming in cheerful royal purple and violet clusters.",
    cost: "$14",
    category: "Flowering & Exotic",
    sunlight: "Bright Indirect Windowsill",
    water: "Bottom-water only (avoid wetting leaves)",
    difficulty: "Easy",
    size: "6-8 inches wide",
    benefit: "Continuous flowering in indoor ambient room temperature.",
    rating: 4.5
  },
  {
    id: 'guzmania-bromeliad',
    name: "Scarlet Star Bromeliad",
    image: "https://cdn.pixabay.com/photo/2016/04/14/17/57/bromeliad-1329388_1280.jpg",
    description: "Vibrant flaming torch of brilliant neon-red and orange flower bracts.",
    cost: "$24",
    category: "Flowering & Exotic",
    sunlight: "Moderate to Bright Filtered Light",
    water: "Keep water filled inside the central leaf cup",
    difficulty: "Easy",
    size: "12-16 inches tall",
    benefit: "Exotic rainforest aesthetic that requires no complicated soil care.",
    rating: 4.6
  },
  {
    id: 'christmas-cactus',
    name: "Holiday Schlumbergera Cactus",
    image: "https://cdn.pixabay.com/photo/2017/12/10/14/47/christmas-cactus-3010078_1280.jpg",
    description: "Jointed arching green leaf pads bursting into fuchsia tiered blossoms in winter.",
    cost: "$16",
    category: "Flowering & Exotic",
    sunlight: "Bright Indirect Sunlight",
    water: "Water thoroughly when top is dry",
    difficulty: "Beginner",
    size: "10-14 inches spread",
    benefit: "Heirloom plant that lives for decades and blooms during holiday months.",
    rating: 4.7
  },
  {
    id: 'indoor-hibiscus',
    name: "Tropical Hibiscus",
    image: "https://cdn.pixabay.com/photo/2016/07/28/09/01/hibiscus-1547372_1280.jpg",
    description: "Huge dinner-plate exotic blooms in fiery red and sunny coral tones.",
    cost: "$22",
    category: "Flowering & Exotic",
    sunlight: "High Bright Sunlight",
    water: "Keep consistently moist during flowering",
    difficulty: "Intermediate",
    size: "20-30 inches tall",
    benefit: "Daily new blooms bring energetic tropical island vibes.",
    rating: 4.6
  },
  {
    id: 'crown-of-thorns',
    name: "Crown of Thorns (Euphorbia)",
    image: "https://cdn.pixabay.com/photo/2018/05/23/16/08/crown-of-thorns-3424458_1280.jpg",
    description: "Spiny stems topped with lush emerald leaves and delicate salmon-pink flowers.",
    cost: "$19",
    category: "Flowering & Exotic",
    sunlight: "Full Sun",
    water: "Drought-tolerant; water every 2-3 weeks",
    difficulty: "Beginner",
    size: "12-18 inches tall",
    benefit: "Blooms reliably all 12 months in dry heated indoor environments.",
    rating: 4.4
  },
  {
    id: 'kalanchoe-blossfeldiana',
    name: "Flaming Katy (Kalanchoe)",
    image: "https://cdn.pixabay.com/photo/2018/02/09/16/22/kalanchoe-3141933_1280.jpg",
    description: "Dense dome of vibrant cherry-red long-lasting miniature flowers.",
    cost: "$12",
    category: "Flowering & Exotic",
    sunlight: "Bright Natural Light",
    water: "Allow soil to dry between waterings",
    difficulty: "Beginner",
    size: "6-10 inches tall",
    benefit: "Succulent foliage that requires very little water while in full flower.",
    rating: 4.5
  },
  {
    id: 'amaryllis-red-lion',
    name: "Amaryllis Red Lion",
    image: "https://cdn.pixabay.com/photo/2017/01/06/19/15/amaryllis-1958671_1280.jpg",
    description: "Gigantic velvety crimson trumpet blooms on stately emerald stalks.",
    cost: "$28",
    category: "Flowering & Exotic",
    sunlight: "Bright Indirect Light",
    water: "Keep lightly moist while actively flowering",
    difficulty: "Easy",
    size: "18-24 inches tall",
    benefit: "Spectacular centerpiece blooms guaranteed to impress guests.",
    rating: 4.8
  },

  // ==========================================
  // 6. FOLIAGE & STATEMENT TREES (10 Plants)
  // ==========================================
  {
    id: 'monstera-deliciosa',
    name: "Monstera Deliciosa (Swiss Cheese Plant)",
    image: "https://cdn.pixabay.com/photo/2020/02/08/17/49/monstera-4830774_1280.jpg",
    description: "Iconic split-leaf tropical climbing plant with dramatic natural fenestrations.",
    cost: "$35",
    category: "Foliage & Ferns",
    sunlight: "Bright Indirect Sunlight",
    water: "Every 1-2 weeks; allow soil to dry partially",
    difficulty: "Easy",
    size: "3-5 feet tall",
    benefit: "Rapidly grows into a lush indoor jungle showpiece.",
    rating: 5.0
  },
  {
    id: 'fiddle-leaf-fig',
    name: "Fiddle Leaf Fig (Ficus lyrata)",
    image: "https://cdn.pixabay.com/photo/2020/09/24/16/12/ficus-lyrata-5600121_1280.jpg",
    description: "Magnificent violin-shaped leathery leaves that command the room.",
    cost: "$45",
    category: "Foliage & Ferns",
    sunlight: "Consistent Bright Filtered Sun",
    water: "When top 2 inches dry out; drain completely",
    difficulty: "Medium",
    size: "4-6 feet tall",
    benefit: "The premier architectural designer tree for modern living rooms.",
    rating: 4.8
  },
  {
    id: 'calathea-medallion',
    name: "Calathea Medallion",
    image: "https://cdn.pixabay.com/photo/2021/04/16/19/20/calathea-6184138_1280.jpg",
    description: "Painterly feathered emerald leaves with rich aubergine-purple undersides.",
    cost: "$24",
    category: "Foliage & Ferns",
    sunlight: "Medium to Low Filtered Light",
    water: "Filtered water; keep moist",
    difficulty: "Intermediate",
    size: "12-18 inches tall",
    benefit: "Foliage folds upwards at night in a charming praying motion.",
    rating: 4.6
  },
  {
    id: 'maidenhair-fern',
    name: "Maidenhair Fern (Adiantum)",
    image: "https://cdn.pixabay.com/photo/2019/08/08/11/33/fern-4392765_1280.jpg",
    description: "Delicate fan-shaped leaflets clustered on glossy ebony-black stems.",
    cost: "$18",
    category: "Foliage & Ferns",
    sunlight: "Dappled Shade & High Humidity",
    water: "Never let soil dry out; loves bathroom humidity",
    difficulty: "Intermediate",
    size: "10-15 inches spread",
    benefit: "Ultra-fine cloud-like texture ideal for terrariums and bathrooms.",
    rating: 4.4
  },
  {
    id: 'stromanthe-triostar',
    name: "Stromanthe Triostar",
    image: "https://cdn.pixabay.com/photo/2021/01/29/08/21/stromanthe-5960093_1280.jpg",
    description: "Exquisite variegated splashes of cream, olive green, and neon magenta-pink.",
    cost: "$26",
    category: "Foliage & Ferns",
    sunlight: "Bright Indirect Light",
    water: "Keep evenly moist with distilled water",
    difficulty: "Medium",
    size: "18-24 inches tall",
    benefit: "Dazzling multi-color palette that rivals flowering plants.",
    rating: 4.7
  },
  {
    id: 'maranta-prayer-plant',
    name: "Red Vein Prayer Plant (Maranta)",
    image: "https://cdn.pixabay.com/photo/2020/04/28/19/26/maranta-5106037_1280.jpg",
    description: "Oval leaves patterned with herringbone neon-red veins and chartreuse centers.",
    cost: "$17",
    category: "Foliage & Ferns",
    sunlight: "Low to Medium Indirect Light",
    water: "Weekly watering with room-temperature water",
    difficulty: "Easy",
    size: "8-12 inches spread",
    benefit: "Non-toxic pet-safe plant with mesmerizing daily movement.",
    rating: 4.7
  },
  {
    id: 'staghorn-fern',
    name: "Staghorn Fern (Platycerium)",
    image: "https://cdn.pixabay.com/photo/2018/09/14/11/33/staghorn-fern-3676882_1280.jpg",
    description: "Epiphytic antler-shaped fronds that can be mounted as living wall art.",
    cost: "$30",
    category: "Foliage & Ferns",
    sunlight: "Bright Diffused Light",
    water: "Soak root ball in water once every 10 days",
    difficulty: "Medium",
    size: "16-24 inches spread",
    benefit: "Can be mounted on reclaimed wood boards as spectacular living sculpture.",
    rating: 4.8
  },
  {
    id: 'philodendron-birkin',
    name: "Philodendron Birkin",
    image: "https://cdn.pixabay.com/photo/2021/02/20/17/41/philodendron-6034015_1280.jpg",
    description: "Dark emerald heart foliage with crisp pinstripes of creamy white variegation.",
    cost: "$23",
    category: "Foliage & Ferns",
    sunlight: "Medium to Bright Indirect Light",
    water: "Allow top half of soil to dry",
    difficulty: "Easy",
    size: "10-16 inches tall",
    benefit: "Compact self-heading philodendron with designer pinstripe leaves.",
    rating: 4.9
  },
  {
    id: 'alocasia-polly',
    name: "Alocasia Amazonica (Polly)",
    image: "https://cdn.pixabay.com/photo/2021/03/09/13/28/alocasia-6081912_1280.jpg",
    description: "Dramatic scalloped arrowhead shield leaves with bold silver-white ribbing.",
    cost: "$27",
    category: "Foliage & Ferns",
    sunlight: "Bright Filtered Light",
    water: "Keep moist during growing season; warm humidity",
    difficulty: "Intermediate",
    size: "14-20 inches tall",
    benefit: "Unique prehistoric African mask look that instantly grabs attention.",
    rating: 4.6
  },
  {
    id: 'schefflera-umbrella',
    name: "Variegated Umbrella Tree (Schefflera)",
    image: "https://cdn.pixabay.com/photo/2020/08/14/15/34/schefflera-5488273_1280.jpg",
    description: "Umbrella whorls of glossy green and gold leaves on an upright shrubby tree.",
    cost: "$22",
    category: "Foliage & Ferns",
    sunlight: "Medium to Bright Light",
    water: "Allow top 2 inches to dry between waterings",
    difficulty: "Easy",
    size: "2-4 feet tall",
    benefit: "Tolerates pruning and shaping into a lush indoor canopy.",
    rating: 4.5
  }
];
